version: "3.5"

services:
  cd:
    image: seocahill/docker-swarm-deploy:latest
    secrets:
      - basic_auth_password
      - docker_stack.yml
      - dockerhub_password
    environment:
      - ALLOWED_SERVICES=my-ruby-service,my-python-service,my-node-service
      - APP_ENV=production
      - DOCKER_USERNAME=my-username
      - WEBHOOK_URL=https://hooks.slack.com/services/my-hook-id
    ports:
      - "4567:4567"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: ash run.sh

secrets:
  basic_auth_password:
    file: basic_auth_password.txt
  docker_stack.yml:
    file: docker-stack.yml
  dockerhub_password:
    file: dockerhub_password
  